/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package letsfightcovid;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class admVaccine1 extends javax.swing.JFrame {
    

    PreparedStatement pst=null;
    /**
     * Creates new form admVaccine
     */
    public admVaccine1() {
        initComponents();
        show_user();
    }
    
     public ArrayList<UserVaccine1> userList()  {
        ArrayList<UserVaccine1> userList = new ArrayList<>();
        try {
            // TODO code application logic here

            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=Covid;user=sa;password=covid12345";
            
            Connection connection = DriverManager.getConnection(url);
            String sql = "Select * from VaccinationCenter ";
            PreparedStatement pst = connection.prepareStatement(sql);
            
            ResultSet rs = pst.executeQuery();
            while(rs.next()){
                UserVaccine1 user = new UserVaccine1(rs.getInt("center_ID"), rs.getString("hospital_name"), rs.getString("center_location"), rs.getString("available_vaccine"));
                userList.add(user);
            
            }
            
        } catch(Exception e){
       JOptionPane.showMessageDialog(null, e);
       }
       return userList;

    }
    public void show_user(){
        ArrayList<UserVaccine1> list =userList();
        DefaultTableModel model = (DefaultTableModel)tablevaccine.getModel();
        Object[] row = new Object[4];
        for(int i=0;i<list.size();i++){
            row[0]=list.get(i).getcenter_ID();
            row[1]=list.get(i).gethospital_name();
            row[2]=list.get(i).getcenter_location();
            row[3]=list.get(i).getavailable_vaccine();
            model.addRow(row);
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        hospital_name = new javax.swing.JTextField();
        center_location = new javax.swing.JTextField();
        available_vaccine = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablevaccine = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        center_id = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CENTER ID");
        jLabel1.setPreferredSize(new java.awt.Dimension(40, 20));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(80, 190, 110, 30);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("HOSPITAL NAME");
        jLabel2.setPreferredSize(new java.awt.Dimension(40, 20));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(80, 240, 120, 30);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CENTER LOCATION");
        jLabel3.setPreferredSize(new java.awt.Dimension(40, 20));
        jPanel1.add(jLabel3);
        jLabel3.setBounds(80, 300, 120, 20);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("AVAILABLE VACCINE");
        jLabel4.setPreferredSize(new java.awt.Dimension(40, 20));
        jPanel1.add(jLabel4);
        jLabel4.setBounds(80, 350, 135, 20);
        jPanel1.add(hospital_name);
        hospital_name.setBounds(230, 240, 130, 30);
        jPanel1.add(center_location);
        center_location.setBounds(230, 290, 130, 30);
        jPanel1.add(available_vaccine);
        available_vaccine.setBounds(230, 350, 130, 30);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("INSERT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(20, 430, 110, 40);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("DELETE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(150, 430, 120, 40);

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton3.setText("UPDATE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(290, 430, 140, 40);

        tablevaccine.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CENTER ID", "HOSPITAL NAME", "CENTER LOCATION", "AVAILABLE VACCINE"
            }
        ));
        jScrollPane1.setViewportView(tablevaccine);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(570, 120, 452, 330);

        jLabel6.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Vaccination Center Information");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(270, 30, 670, 60);
        jPanel1.add(center_id);
        center_id.setBounds(230, 190, 130, 30);

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton4.setText("Back To Menu");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(910, 480, 200, 50);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BgPic.jpg"))); // NOI18N
        jLabel5.setPreferredSize(new java.awt.Dimension(1150, 550));
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 0, 1150, 550);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1149, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=Covid;user=sa;password=covid12345";
            

            Connection con = DriverManager.getConnection(url);
            String sql ="INSERT into VaccinationCenter(hospital_name,center_location,available_vaccine) values(?,?,?)";
            pst = con.prepareStatement(sql);
            pst.setString(1,hospital_name.getText());
            pst.setString(2,center_location.getText());
            pst.setString(3,available_vaccine.getText());
            pst.executeUpdate();
            DefaultTableModel model=(DefaultTableModel)tablevaccine.getModel();
            model.setRowCount(0);
            show_user();
            JOptionPane.showMessageDialog(null,"Data Saved Sucessfully");
        
        }catch(Exception e){
        
        JOptionPane.showMessageDialog(null,e);        
        }        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=Covid;user=sa;password=covid12345";
            
            Connection con = DriverManager.getConnection(url);
            int row = tablevaccine.getSelectedRow();
            String value =(tablevaccine.getModel().getValueAt(row, 0).toString());
            String query1 = "DELETE FROM VaccinationCenter WHERE center_ID="+value;
            PreparedStatement pst =con.prepareStatement(query1);
            pst.executeUpdate();
            DefaultTableModel model=(DefaultTableModel)tablevaccine.getModel();
            model.setRowCount(0);
            show_user();
            JOptionPane.showMessageDialog(null, "Deleted Successfully");
            
         } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);

        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       try{
              Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
              String url = "jdbc:sqlserver://localhost:1433;databaseName=Covid;user=sa;password=covid12345";
        
            Connection con = DriverManager.getConnection(url);
            int row =tablevaccine.getSelectedRow();
            String value = (tablevaccine.getModel().getValueAt(row, 0).toString());
            String query1="Update VaccinationCenter Set hospital_name=?,center_location=?,available_vaccine=? where center_ID="+value;
            PreparedStatement ps= con.prepareStatement(query1);
            //ps.setString(6, jTextField6.getText());
           //ps.setString(4, center_id.getText());
            ps.setString(1, hospital_name.getText());
            ps.setString(2, center_location.getText());
            ps.setString(3, available_vaccine.getText());
            ps.executeUpdate();
            
           DefaultTableModel model = (DefaultTableModel)tablevaccine.getModel();
           model.setRowCount(0);
        
        show_user();
        JOptionPane.showMessageDialog(null,"Updated Successfully");
        
        }catch(Exception e){
        
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        MenuAdm m = new MenuAdm();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admVaccine1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admVaccine1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admVaccine1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admVaccine1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admVaccine1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField available_vaccine;
    private javax.swing.JTextField center_id;
    private javax.swing.JTextField center_location;
    private javax.swing.JTextField hospital_name;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablevaccine;
    // End of variables declaration//GEN-END:variables
}
