/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package letsfightcovid;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class HospitalUser extends javax.swing.JFrame {

    /**
     * Creates new form Hospital
     */
    public HospitalUser() {
        initComponents();
         show_user();
    }
      public ArrayList<User1> userList() {
       ArrayList<User1> userList = new ArrayList<>();
       
       try{
           Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=Covid;user=sa;password=covid12345";
            
            Connection connection = DriverManager.getConnection(url);
            String query1="SELECT * FROM Hospital";
            Statement st=connection.createStatement();
            ResultSet rs=st.executeQuery(query1);
            User1 user;
            while(rs.next()){
                user=new User1(rs.getInt("hospital_ID"), rs.getString("hospital_Name"), rs.getString("hospital_address"), rs.getString("hospital_contact"));
                userList.add(user);
            }
       }
       catch(Exception e){
       JOptionPane.showMessageDialog(null, e);
       }
       return userList;
    }
    
    public void show_user() {
         ArrayList<User1> list =userList();
        DefaultTableModel model = (DefaultTableModel)table.getModel();
        Object[] row= new Object[4];
        for(int i=0 ; i<list.size(); i++){
        
         row[0]=list.get(i).gethospital_ID();
          row[1]=list.get(i).gethospital_Name();
           row[2]=list.get(i).gethospital_address();
            row[3]=list.get(i).gethospital_contact();
            model.addRow(row);
         
     }
    
    
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textFieldSearch = new javax.swing.JTextField();
        comboBoxSelection = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        textFieldSearch.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        textFieldSearch.setForeground(new java.awt.Color(51, 51, 51));
        textFieldSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textFieldSearchKeyReleased(evt);
            }
        });
        jPanel1.add(textFieldSearch);
        textFieldSearch.setBounds(700, 510, 320, 40);

        comboBoxSelection.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        comboBoxSelection.setForeground(new java.awt.Color(255, 255, 255));
        comboBoxSelection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hospital ID", "Hospital Name", "Hospital Address" }));
        jPanel1.add(comboBoxSelection);
        comboBoxSelection.setBounds(390, 512, 230, 40);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText(" Back To Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(60, 510, 170, 40);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Hospital ID", "Hospital Name", "Hospital Address", "Hospital Contact"
            }
        ));
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 100, 1080, 380);

        jLabel1.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("HOSPITAL INFORMATION");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(370, 30, 410, 48);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BgPic.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 1160, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldSearchKeyReleased
        // TODO add your handling code here:
        
         DefaultTableModel model= (DefaultTableModel) table.getModel();
          model.setRowCount(0);
          
          try {
            // TODO code application logic here

            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=Covid;user=sa;password=covid12345";
            Connection connection = DriverManager.getConnection(url);
            
             String selection=(String)comboBoxSelection.getSelectedItem();
            String query="";
            if(comboBoxSelection.getSelectedIndex()==0){
            query="select * from Hospital where hospital_ID= "+textFieldSearch.getText();
            }
           if(comboBoxSelection.getSelectedIndex()==1){
           query="select * from Hospital where hospital_Name LIKE '%"+textFieldSearch.getText()+"%'";
            }
           if(comboBoxSelection.getSelectedIndex()==2){
            query="select * from Hospital where hospital_address LIKE '"+textFieldSearch.getText()+"%'";
           }
            
            
            System.out.println(query);
            PreparedStatement pst=connection.prepareStatement(query);
        //    pst.setString(1, textFieldSearch.getText());
            ResultSet rs=pst.executeQuery();
           while(rs.next()) {
               String s[]={rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4)};
              model.addRow(s);
              
           }
            
          
          
          } catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_textFieldSearchKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
         Menu2 m = new Menu2();
        m.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HospitalUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HospitalUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HospitalUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HospitalUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HospitalUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBoxSelection;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JTextField textFieldSearch;
    // End of variables declaration//GEN-END:variables
}
