/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package letsfightcovid;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Richi
 */
public class loginpage1 extends javax.swing.JFrame {

    
    public loginpage1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userName = new javax.swing.JTextField();
        checkBox = new javax.swing.JCheckBox();
        loginBttn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        resigterBttn = new javax.swing.JButton();
        passwords = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Stencil", 1, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 51, 255));
        jLabel1.setText("Log In here !!!");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 26, 646, 93));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 317, -1, 48));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("User Id");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 217, -1, 54));

        userName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        userName.setForeground(new java.awt.Color(153, 153, 153));
        getContentPane().add(userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 217, 309, 54));

        checkBox.setBackground(new java.awt.Color(204, 102, 255));
        checkBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        checkBox.setForeground(new java.awt.Color(255, 255, 255));
        checkBox.setText("Show Password");
        checkBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxActionPerformed(evt);
            }
        });
        getContentPane().add(checkBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 383, 130, -1));

        loginBttn.setBackground(new java.awt.Color(153, 0, 204));
        loginBttn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        loginBttn.setForeground(new java.awt.Color(255, 255, 255));
        loginBttn.setText("Login");
        loginBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBttnActionPerformed(evt);
            }
        });
        getContentPane().add(loginBttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 443, 99, 40));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 102, 255));
        jLabel4.setText("Not a member?");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 524, 175, 48));

        resigterBttn.setBackground(new java.awt.Color(102, 0, 204));
        resigterBttn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        resigterBttn.setForeground(new java.awt.Color(255, 255, 255));
        resigterBttn.setText("Register Here");
        resigterBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resigterBttnActionPerformed(evt);
            }
        });
        getContentPane().add(resigterBttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 524, 165, 48));

        passwords.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        passwords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordsActionPerformed(evt);
            }
        });
        getContentPane().add(passwords, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 309, 309, 56));

        jPanel1.setLayout(null);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(153, 0, 0));
        jButton2.setText("Back to Menu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(930, 515, 160, 50);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BgPic.jpg"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 0, 1140, 590);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxActionPerformed
        if(checkBox.isSelected())
        {
            passwords.setEchoChar((char)0);
        }

        else
        {
            passwords.setEchoChar('*');
        }

    }//GEN-LAST:event_checkBoxActionPerformed

    private void loginBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBttnActionPerformed
        String usrName = userName.getText();
        String pass = passwords.getText();

        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=Covid;user=sa;password=covid12345";

            Connection con = DriverManager.getConnection(url);
            String user = userName.getText();
            String sql = "select * from MEMBERS where userName ='" + userName.getText() + "' and passwords ='" + passwords.getText() + "'";

            PreparedStatement pst = con.prepareStatement(sql);

            ResultSet rs = pst.executeQuery();

            if(userName.getText().equals(""))
            {
                JOptionPane.showMessageDialog(null,"You have not entered your UserName!");
            }
            else if(passwords.getText().equals(""))
            {
                JOptionPane.showMessageDialog(null,"You have not entered your password!");
            }

            else if(rs.next())
            {
                new Menu2().setVisible(true);
                this.dispose();
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Invalid Information!");
            }

            //System.out.println(serial+" "+usrName+" "+pass);
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex);
        }

    }//GEN-LAST:event_loginBttnActionPerformed

    private void resigterBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resigterBttnActionPerformed
        new registerForm1().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_resigterBttnActionPerformed

    private void passwordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordsActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Menu m = new Menu();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginpage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginpage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginpage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginpage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginpage1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkBox;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginBttn;
    private javax.swing.JPasswordField passwords;
    private javax.swing.JButton resigterBttn;
    private javax.swing.JTextField userName;
    // End of variables declaration//GEN-END:variables
}
