/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package letsfightcovid;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 * 
 * 
 */



public class PurchaseKit extends javax.swing.JFrame {

    /**
     * Creates new form PurchaseKit
     */
    public PurchaseKit() {
        initComponents();
    }
    
    Connection con;
    PreparedStatement pst;
    PreparedStatement pst1;

    DefaultTableModel model;
    String item;
    int price;
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelHeading = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnprint = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtqty = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        txtpay = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtbal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        btnKm = new javax.swing.JRadioButton();
        btnSm = new javax.swing.JRadioButton();
        btnOx = new javax.swing.JRadioButton();
        btnIR = new javax.swing.JRadioButton();
        btnHand = new javax.swing.JRadioButton();
        btnPPE = new javax.swing.JRadioButton();
        btnFace = new javax.swing.JRadioButton();
        btnGlov = new javax.swing.JRadioButton();
        btnGog = new javax.swing.JRadioButton();
        btnRemove = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabelHeading.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelHeading.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHeading.setText("Purchase kit");
        jPanel1.add(jLabelHeading);
        jLabelHeading.setBounds(420, 20, 250, 50);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "product_name", "price_per_unit", "Quantity", "Total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(320, 100, 640, 280);

        btnAdd.setText("Add Item ");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd);
        btnAdd.setBounds(310, 420, 130, 50);

        btnprint.setText("Calculate Price");
        btnprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprintActionPerformed(evt);
            }
        });
        jPanel1.add(btnprint);
        btnprint.setBounds(470, 420, 150, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Quantity");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(1030, 70, 100, 30);
        jPanel1.add(txtqty);
        txtqty.setBounds(1030, 110, 100, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Payment");
        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel3);
        jLabel3.setBounds(1030, 260, 100, 30);

        txtpay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpayActionPerformed(evt);
            }
        });
        jPanel1.add(txtpay);
        txtpay.setBounds(1030, 310, 100, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Balance");
        jLabel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel4);
        jLabel4.setBounds(1030, 370, 100, 40);
        jPanel1.add(txtbal);
        txtbal.setBounds(1030, 430, 100, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Total");
        jLabel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel5);
        jLabel5.setBounds(1030, 160, 100, 30);
        jPanel1.add(txttotal);
        txttotal.setBounds(1030, 200, 100, 30);

        btnKm.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btnKm.setForeground(new java.awt.Color(255, 255, 255));
        btnKm.setText("K-95 Mask");
        jPanel1.add(btnKm);
        btnKm.setBounds(90, 130, 150, 33);

        btnSm.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btnSm.setForeground(new java.awt.Color(255, 255, 255));
        btnSm.setText("Sugical Mask");
        jPanel1.add(btnSm);
        btnSm.setBounds(90, 170, 150, 33);

        btnOx.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btnOx.setForeground(new java.awt.Color(255, 255, 255));
        btnOx.setText("Oximeter");
        jPanel1.add(btnOx);
        btnOx.setBounds(90, 210, 150, 33);

        btnIR.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btnIR.setForeground(new java.awt.Color(255, 255, 255));
        btnIR.setText("IR Thermometer");
        jPanel1.add(btnIR);
        btnIR.setBounds(90, 250, 180, 33);

        btnHand.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btnHand.setForeground(new java.awt.Color(255, 255, 255));
        btnHand.setText("Hand Sanitiser");
        btnHand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHandActionPerformed(evt);
            }
        });
        jPanel1.add(btnHand);
        btnHand.setBounds(90, 290, 150, 30);

        btnPPE.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btnPPE.setForeground(new java.awt.Color(255, 255, 255));
        btnPPE.setText("PPE");
        jPanel1.add(btnPPE);
        btnPPE.setBounds(90, 340, 150, 33);

        btnFace.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btnFace.setForeground(new java.awt.Color(255, 255, 255));
        btnFace.setText("Face Shield");
        jPanel1.add(btnFace);
        btnFace.setBounds(90, 390, 150, 33);

        btnGlov.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btnGlov.setForeground(new java.awt.Color(255, 255, 255));
        btnGlov.setText("Gloves");
        jPanel1.add(btnGlov);
        btnGlov.setBounds(90, 440, 150, 33);

        btnGog.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btnGog.setForeground(new java.awt.Color(255, 255, 255));
        btnGog.setText("Goggles");
        jPanel1.add(btnGog);
        btnGog.setBounds(90, 490, 150, 33);

        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        jPanel1.add(btnRemove);
        btnRemove.setBounds(840, 420, 160, 50);

        jButton1.setText("Back To Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(230, 540, 150, 40);

        jButton2.setText("Log Out");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(860, 540, 100, 30);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon4-removebg-preview (2).png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(10, 10, 70, 70);

        jButton4.setText("Print Payslip");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(660, 420, 130, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BgPic.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1150, 599);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 80, 310, 470);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1148, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        
        if(btnKm.isSelected() == true)
        {
            item = "K-95 Mask";
            price = 60;
        }
        else if(btnSm.isSelected() == true)
        {
            item = "Surgical Mask";
            price = 10;
        }
           else if(btnOx.isSelected() == true)
        {
            item = "Oximeter";
            price = 300;
        }
         else if(btnIR.isSelected() == true)
        {
            item = "Infrared Thermometer";
            price = 400;
        }
        
        else if(btnHand.isSelected() == true)
        {
            item = "Hand Sanitiser";
            price = 80;
        }
        else if(btnPPE.isSelected() == true)
        {
            item = "PPE";
            price = 500;
        }
        else if(btnFace.isSelected() == true)
        {
            item = "Face Shield";
            price = 200;
        }
        else if(btnGlov.isSelected() == true)
        {
            item = "Gloves";
            price = 20;
        }
        else if(btnGog.isSelected() == true)
        {
            item = "Goggles";
            price = 120;
        }
        
        int qty = Integer.parseInt(txtqty.getValue().toString());
        int tot = qty * price;
        
        model = (DefaultTableModel)jTable1.getModel();
        
        model.addRow(new Object[]
                
        {
            item,
            price,
            qty,
            tot
            
        });
        
        int sum = 0;
        
        for(int a=0; a<jTable1.getRowCount(); a++)
        {
            sum = sum + Integer.parseInt(jTable1.getValueAt(a, 3).toString());
        }
        txttotal.setText(Integer.toString(sum));
        
        
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprintActionPerformed
        // TODO add your handling code here:
        int tot = Integer.parseInt(txttotal.getText());
        int pay = Integer.parseInt(txtpay.getText());
        
        int bal = pay - tot;
        
        txtbal.setText(String.valueOf(bal));
        
        
        try {
            payment();
        } catch (SQLException ex) {
            Logger.getLogger(PurchaseKit.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnprintActionPerformed

    private void txtpayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpayActionPerformed

    private void btnHandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHandActionPerformed

    public void payment() throws SQLException{
        int lastid =0;
       try {
           Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=Covid;user=sa;password=covid12345";
            con = DriverManager.getConnection(url);
           
            String total = txttotal.getText();
            String pay = txtpay.getText();
            String bal = txtbal.getText();
            
            
            
            String query = "insert into Payment(subtotal,pay,bal)values(?,?,?)";
            pst = con.prepareStatement(query,Statement.RETURN_GENERATED_KEYS);
            pst.setString(1, total);
            pst.setString(2, pay);
            pst.setString(3, bal);
            pst.executeUpdate();
             ResultSet rs = pst.getGeneratedKeys();
            
            if(rs.next())
            {
                lastid = rs.getInt(1);
            }
            int row = jTable1.getRowCount();
            String query1 = "insert into PurchaseKit(sales_id,product_name,price_per_unit,quantity,total)values(?,?,?,?,?)";
            pst1 = con.prepareStatement(query1);
            
            String prodname = "";
            int price;
            int qty;
            int tot = 0;
 
            for(int i=0; i<jTable1.getRowCount(); i++)
                    {
                        prodname = (String)jTable1.getValueAt(i, 0);
                         price = (int)jTable1.getValueAt(i, 1);
                         qty = (int)jTable1.getValueAt(i, 2);
                         tot = (int)jTable1.getValueAt(i, 3);
                        
                         pst1.setInt(1,lastid);
                          pst1.setString(2,prodname);
                          pst1.setInt(3,price);
                          pst1.setInt(4,qty);
                          pst1.setInt(5,tot);
                          pst1.executeUpdate();
                        
                    }
             JOptionPane.showMessageDialog(this, "Saless Completeeeeddddddd");
        
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PurchaseKit.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        
        model.removeRow(jTable1.getSelectedRow());
         int sum = 0;
         for(int a=0; a<jTable1.getRowCount(); a++)
        {
            
            sum = sum + Integer.parseInt(jTable1.getValueAt(a, 3).toString());
            
        }
        txttotal.setText(Integer.toString(sum));
        
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        Menu2 m = new Menu2();
        m.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        loginpage1 obj = new loginpage1();
       obj.setVisible(true);
       dispose();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Profile1 p = new Profile1();
        p.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        PaymentSlip p = new PaymentSlip();
        p.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PurchaseKit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PurchaseKit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PurchaseKit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PurchaseKit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PurchaseKit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JRadioButton btnFace;
    private javax.swing.JRadioButton btnGlov;
    private javax.swing.JRadioButton btnGog;
    private javax.swing.JRadioButton btnHand;
    private javax.swing.JRadioButton btnIR;
    private javax.swing.JRadioButton btnKm;
    private javax.swing.JRadioButton btnOx;
    private javax.swing.JRadioButton btnPPE;
    private javax.swing.JButton btnRemove;
    private javax.swing.JRadioButton btnSm;
    private javax.swing.JButton btnprint;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelHeading;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtbal;
    private javax.swing.JTextField txtpay;
    private javax.swing.JSpinner txtqty;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
